# Generated by Django 3.0.3 on 2020-06-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ages', models.IntegerField(blank=True, null=True)),
                ('area1', models.TextField(blank=True, null=True)),
                ('area2', models.TextField(blank=True, null=True)),
                ('gender', models.IntegerField(blank=True, null=True)),
                ('is_inst', models.IntegerField(default=0)),
                ('profile_image', models.TextField(blank=True, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_area', models.TextField(blank=True, null=True)),
                ('second_area', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_description', models.TextField()),
                ('category_name', models.TextField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('chatting_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'chatting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'interest_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LikeMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'like_meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_period', models.IntegerField()),
                ('meeting_date', models.DateTimeField()),
                ('period_date', models.TextField()),
                ('is_class', models.IntegerField()),
                ('max_person', models.IntegerField()),
                ('now_person', models.IntegerField()),
                ('content', models.TextField()),
                ('ref_url', models.TextField(blank=True, null=True)),
                ('fee', models.IntegerField()),
                ('unit', models.TextField()),
                ('is_active', models.IntegerField()),
                ('like_cnt', models.IntegerField()),
                ('view_cnt', models.IntegerField()),
                ('score', models.FloatField()),
                ('tags', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('area1', models.TextField(blank=True, null=True)),
                ('area2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeetingImages',
            fields=[
                ('meeting_images_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'meeting_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
                ('image_url', models.TextField(blank=True, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('openness', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('extraversion', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
            ],
            options={
                'db_table': 'survey',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'user_meeting',
                'managed': False,
            },
        ),
    ]
