# Generated by Django 3.0.3 on 2020-06-02 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('profile_image', models.TextField(null=True)),
                ('is_inst', models.IntegerField(default=0)),
                ('gender', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('ages', models.IntegerField(null=True)),
                ('area1', models.TextField(null=True)),
                ('area2', models.TextField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_area', models.TextField()),
                ('second_area', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField()),
                ('category_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_period', models.IntegerField()),
                ('meeting_date', models.DateTimeField()),
                ('period_date', models.TextField()),
                ('is_class', models.IntegerField()),
                ('max_person', models.IntegerField()),
                ('now_person', models.IntegerField()),
                ('content', models.TextField()),
                ('ref_url', models.TextField()),
                ('address', models.TextField()),
                ('fee', models.IntegerField()),
                ('unit', models.TextField()),
                ('is_active', models.IntegerField()),
                ('like_cnt', models.IntegerField()),
                ('view_cnt', models.IntegerField()),
                ('score', models.FloatField()),
                ('tags', models.TextField()),
                ('title', models.TextField()),
                ('area1', models.TextField()),
                ('area2', models.TextField()),
                ('main_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='api.Category')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.IntegerField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMeeting', to='api.Meeting')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userMeeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('survey_id', models.AutoField(primary_key=True, serialize=False)),
                ('openness', models.IntegerField()),
                ('conscientiousness', models.IntegerField()),
                ('extraversion', models.IntegerField()),
                ('agreeableness', models.IntegerField()),
                ('neuroticism', models.IntegerField()),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.IntegerField()),
                ('image_url', models.TextField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.Meeting')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.TextField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetingImages', to='api.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='LikeMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeMeeting', to='api.Meeting')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likeMeeting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interestCategory', to='api.Category')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interestCategory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('chatting_id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('meeting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatting', to='api.Meeting')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
