# Generated by Django 3.0.3 on 2020-06-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200604_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area1',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='area2',
            field=models.TextField(blank=True, default='대전광역시'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.TextField(blank=True, default='유성구'),
            preserve_default=False,
        ),
    ]
